[global/wm]

margin-bottom = 0
margin-top = 0
fixed-center = true

include-file = $HOME/.config/polybar/colors.ini

[bar/main]

; Items position
modules-left = rSide date lSide sep rSide alsa spotify lSide
modules-center = rSide xwindow lSide  
modules-right =  rSide cpu  space space memory lSide sep rSide network lSide


monitor-fallback =
monitor-strict = false
override-redirect = false

background = 
foreground = ${color.fg}
dim-value = 1.0

bottom = false
fixed-center = true
padding = 0
width = 100%
height = 31
offset-x = 0%
offset-y = 0%
radius-top = 0
radius-bottom = 0

line-size = 2
line-color = ${color.bg}
tray-position = right
tray-detached = false
tray-maxsize = 16
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
border-top-size = 5
border-left-size = 6
border-right-size = 6

font-0 = "Iosevka Nerd Font:size=10;2"
font-1 = "Iosevka Nerd Font:style=Medium:size=18;4"
font-2 = "feather:size=11;3"


; ==================> MODULES <==================

[glyph]
gleft = 
gright = 

[module/lSide]
type = custom/text
content-foreground = ${color.bg}
content = ${glyph.gleft}
content-font = 2

[module/rSide]
type = custom/text
content-foreground = ${color.bg}
content = ${glyph.gright}
content-font = 2

[module/sep]
type = custom/text
content = " "

[module/space]
type = custom/text
content = " "
content-foreground = ${color.bg}
content-background = ${color.bg}

[module/date]
type = internal/date
interval = 1
time = %H:%M
date-alt = %A %d %B
format = <label>
format-prefix = " "
format-prefix-foreground = ${color.red}
format-background = ${color.bg}
label = %date% %time%

[module/memory]
type = internal/memory
interval = 1
format = <label>
format-prefix = 
format-prefix-foreground = ${color.purple}
format-background = ${color.bg}
label = " %gb_used%"

[module/network]
type = internal/network
interface = enp7s0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
format-connected = <label-connected>
format-connected-prefix = 
format-connected-prefix-foreground = ${color.orange}
format-connected-background = ${color.bg}
format-connected-padding = 0
format-disconnected = <label-disconnected>
format-disconnected-prefix = 
format-disconnected-prefix-foreground = ${color.red}
format-disconnected-background = ${color.bg}
format-disconnected-padding = 0
label-connected = "%{A1:networkmanager_dmenu &:} %downspeed%%{A} - %local_ip%"
label-disconnected = "%{A1:networkmanager_dmenu &:} Offline%{A}"

[module/alsa]
type = internal/alsa
interval = 5
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master
format-volume = <ramp-volume> <label-volume>
format-volume-background = ${color.bg}
format-muted = <label-muted>
format-muted-background = ${color.bg}
label-volume = %percentage%%
label-muted = 
label-muted-foreground =${color.red}
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-headphones-0 = 
ramp-volume-foreground = ${color.blue}

[module/xwindow]
type = internal/xwindow
label = %title%
format-background = ${color.bg}

[module/cpu]
type = internal/cpu
interval = 1
format = <label>
format-prefix = 
format-prefix-foreground = ${color.green}
format-background = ${color.bg}
label = " %percentage%%"

; =========> POLYBAR SETTINGS HERE 

[settings]

throttle-output = 2
throttle-output-for = 10
screenchange-reload = true
